export interface FontOption {
  name: string;
  stack: string;
  category: 'script' | 'serif' | 'sans';
}

export const FONT_OPTIONS: FontOption[] = [
  { name: 'Cormorant Garamond', stack: "'Cormorant Garamond', serif", category: 'serif' },
  { name: 'Playfair Display', stack: "'Playfair Display', serif", category: 'serif' },
  { name: 'EB Garamond', stack: "'EB Garamond', serif", category: 'serif' },
  { name: 'Lora', stack: "'Lora', serif", category: 'serif' },
  { name: 'Libre Baskerville', stack: "'Libre Baskerville', serif", category: 'serif' },
  { name: 'Marcellus', stack: "'Marcellus', serif", category: 'serif' },
  { name: 'Cardo', stack: "'Cardo', serif", category: 'serif' },
  { name: 'Spectral', stack: "'Spectral', serif", category: 'serif' },
  { name: 'Source Serif 4', stack: "'Source Serif 4', serif", category: 'serif' },
  { name: 'Cinzel', stack: "'Cinzel', serif", category: 'serif' },
  { name: 'Cormorant', stack: "'Cormorant', serif", category: 'serif' },
  { name: 'Crimson Pro', stack: "'Crimson Pro', serif", category: 'serif' },
  { name: 'Frank Ruhl Libre', stack: "'Frank Ruhl Libre', serif", category: 'serif' },
  { name: 'Josefin Slab', stack: "'Josefin Slab', serif", category: 'serif' },
  { name: 'Prata', stack: "'Prata', serif", category: 'serif' },
  { name: 'Zilla Slab', stack: "'Zilla Slab', serif", category: 'serif' },
  { name: 'Great Vibes', stack: "'Great Vibes', cursive", category: 'script' },
  { name: 'Dancing Script', stack: "'Dancing Script', cursive", category: 'script' },
  { name: 'Sacramento', stack: "'Sacramento', cursive", category: 'script' },
  { name: 'Parisienne', stack: "'Parisienne', cursive", category: 'script' },
  { name: 'Tangerine', stack: "'Tangerine', cursive", category: 'script' },
  { name: 'Allura', stack: "'Allura', cursive", category: 'script' },
  { name: 'Pinyon Script', stack: "'Pinyon Script', cursive", category: 'script' },
  { name: 'Alex Brush', stack: "'Alex Brush', cursive", category: 'script' },
  { name: 'Arizonia', stack: "'Arizonia', cursive", category: 'script' },
  { name: 'Bilbo Swash Caps', stack: "'Bilbo Swash Caps', cursive", category: 'script' },
  { name: 'Cookie', stack: "'Cookie', cursive", category: 'script' },
  { name: 'Euphoria Script', stack: "'Euphoria Script', cursive", category: 'script' },
  { name: 'Italianno', stack: "'Italianno', cursive", category: 'script' },
  { name: 'Kristi', stack: "'Kristi', cursive", category: 'script' },
  { name: 'Marck Script', stack: "'Marck Script', cursive", category: 'script' },
  { name: 'Mr Dafoe', stack: "'Mr Dafoe', cursive", category: 'script' },
  { name: 'Mrs Saint Delafield', stack: "'Mrs Saint Delafield', cursive", category: 'script' },
  { name: 'Petit Formal Script', stack: "'Petit Formal Script', cursive", category: 'script' },
  { name: 'Pristina', stack: "'Pristina', cursive", category: 'script' },
  { name: 'Qwigley', stack: "'Qwigley', cursive", category: 'script' },
  { name: 'Satisfy', stack: "'Satisfy', cursive", category: 'script' },
  { name: 'Spirax', stack: "'Spirax', cursive", category: 'script' },
  { name: 'Yellowtail', stack: "'Yellowtail', cursive", category: 'script' },
  { name: 'Montserrat', stack: "'Montserrat', sans-serif", category: 'sans' },
  { name: 'Lato', stack: "'Lato', sans-serif", category: 'sans' },
  { name: 'Open Sans', stack: "'Open Sans', sans-serif", category: 'sans' },
  { name: 'Raleway', stack: "'Raleway', sans-serif", category: 'sans' },
  { name: 'Work Sans', stack: "'Work Sans', sans-serif", category: 'sans' },
  { name: 'Inter', stack: "'Inter', sans-serif", category: 'sans' },
  { name: 'Mulish', stack: "'Mulish', sans-serif", category: 'sans' },
  { name: 'Poppins', stack: "'Poppins', sans-serif", category: 'sans' },
  { name: 'Nunito', stack: "'Nunito', sans-serif", category: 'sans' },
  { name: 'Quicksand', stack: "'Quicksand', sans-serif", category: 'sans' },
  { name: 'Outfit', stack: "'Outfit', sans-serif", category: 'sans' },
  { name: 'Jost', stack: "'Jost', sans-serif", category: 'sans' },
];

const PRELOAD_FONTS = [
  'Cormorant Garamond:wght@400;500;600;700',
  'Playfair Display:wght@400;500;600;700;800;900',
  'EB Garamond:wght@400;500;600;700',
  'Lora:wght@400;500;600;700',
  'Libre Baskerville:wght@400;700',
  'Marcellus',
  'Cardo:wght@400;700',
  'Spectral:wght@400;500;600;700',
  'Source Serif 4:wght@400;600;700',
  'Cinzel:wght@400;500;600;700',
  'Cormorant:wght@400;500;600;700',
  'Crimson Pro:wght@400;500;600;700',
  'Frank Ruhl Libre:wght@400;500;700',
  'Josefin Slab:wght@400;500;700',
  'Prata',
  'Zilla Slab:wght@400;500;600;700',
  'Great Vibes',
  'Dancing Script:wght@400;500;600;700',
  'Sacramento',
  'Parisienne',
  'Tangerine:wght@400;700',
  'Allura',
  'Pinyon Script',
  'Alex Brush',
  'Arizonia',
  'Bilbo Swash Caps',
  'Cookie',
  'Euphoria Script',
  'Italianno',
  'Kristi',
  'Marck Script',
  'Mr Dafoe',
  'Mrs Saint Delafield',
  'Petit Formal Script',
  'Pristina',
  'Qwigley',
  'Satisfy',
  'Spirax',
  'Yellowtail',
  'Montserrat:wght@300;400;500;600;700',
  'Lato:wght@300;400;700',
  'Open Sans:wght@400;500;600;700',
  'Raleway:wght@300;400;500;600;700',
  'Work Sans:wght@300;400;500;600;700',
  'Inter:wght@300;400;500;600;700',
  'Mulish:wght@300;400;500;600;700',
  'Poppins:wght@300;400;500;600;700',
  'Nunito:wght@300;400;500;600;700',
  'Quicksand:wght@300;400;500;600;700',
  'Outfit:wght@300;400;500;600;700',
  'Jost:wght@300;400;500;600;700',
];

export function fontHref() {
  return `https://fonts.googleapis.com/css2?${PRELOAD_FONTS.map((f) => f.replace(/ /g, '+')).join('&')}&display=swap`;
}

export function stackFor(name: string): string {
  return FONT_OPTIONS.find((f) => f.name === name)?.stack ?? name;
}

export function categoryLabel(cat: string): string {
  return cat === 'script' ? 'Script / Calligraphy' : cat === 'serif' ? 'Serif / Elegant' : 'Sans-serif / Modern';
}
